spring.application.name=bybills-backend

spring.datasource.url=jdbc:mysql://localhost:3306/bybills
spring.datasource.username=root
spring.datasource.password=saitejasri

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080