spring.application.name=bybills-backend
spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:21084/railway
spring.datasource.username=root
spring.datasource.password=ZsSLmGFafcgctEzuvvLcSieoyzILMmxJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
